APP_NAME = bbfm

CONFIG += qt warn_on cascades10

QMAKE_CFLAGS_RELEASE += -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16
QMAKE_CXXFLAGS_RELEASE += -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16

QMAKE_CFLAGS_DEBUG += -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16
QMAKE_CXXFLAGS_DEBUG += -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16

LIBS += -lbb

include(config.pri)
